# Generated by Django 5.0.2 on 2024-05-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretary', '0005_returnitemhistory_borrower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnitemhistory',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
