# Generated by Django 5.0.2 on 2024-04-11 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretary', '0002_delete_staff'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
